
services:
  bot:
    build: .
    restart: always
    env_file:
      - ./bot/.env           # путь к твоему .env внутри папки bot
    volumes:
      - ./bot.db:/app/bot.db # монтируем локальную SQLite-базу внутрь контейнера
    working_dir: /app        # корневая директория, где находится папка bot
    command: python -m bot.main
